**KÜTÜPHANELERİ ÇAĞIRMA VE VERİ KÜMESİNİ OKUMA**

In [46]:
import numpy as np
import pandas as pd
#Excel Dosyası Okuma
dataset = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/pisa2009test.xlsx')
#Veri Tiplerinin Çıktısı
print(dataset.dtypes)
dataset

grade                      int64
raceeth                   object
preschool                float64
expectBachelors          float64
motherHS                 float64
motherBachelors          float64
motherWork               float64
fatherHS                 float64
fatherBachelors          float64
fatherWork               float64
selfBornUS               float64
motherBornUS             float64
fatherBornUS             float64
englishAtHome            float64
computerForSchoolwork    float64
read30MinsADay           float64
minutesPerWeekEnglish    float64
studentsInEnglish        float64
schoolHasLibrary         float64
publicSchool               int64
urban                      int64
schoolSize               float64
readingScore               int64
male                       int64
dtype: object


grade   raceeth  preschool  ...  schoolSize  readingScore  male
0        10     White        1.0  ...       808.0         35524     0
1        10     White        0.0  ...       808.0         38557     1
2        10     White        1.0  ...       808.0         52262     0
3        10     White        1.0  ...       808.0         40624     0
4        10     White        1.0  ...       808.0          4535     0
...     ...       ...        ...  ...         ...           ...   ...
1565      9     White        1.0  ...       987.0         46558     1
1566     11     White        1.0  ...       987.0         38018     0
1567     10  Hispanic        1.0  ...       987.0          3241     0
1568     10     White        1.0  ...       987.0         59634     0
1569     10     White        1.0  ...       987.0         57743     0

[1570 rows x 24 columns]

**VERİ KÜMESİNDE BULUNAN KOLONLARIN İÇERİSİNDEKİ NaN DEĞERLER**

In [47]:
print(dataset.isnull().sum().sort_values(ascending=False))

fatherBachelors          288
motherBachelors          188
fatherHS                 125
studentsInEnglish        114
fatherWork               113
minutesPerWeekEnglish    103
schoolSize                69
fatherBornUS              58
schoolHasLibrary          58
motherHS                  45
motherWork                36
computerForSchoolwork     30
englishAtHome             27
selfBornUS                24
expectBachelors           23
motherBornUS              23
read30MinsADay            21
preschool                 21
raceeth                    0
male                       0
readingScore               0
publicSchool               0
urban                      0
grade                      0
dtype: int64


**KOLONLARDAKİ VERİ SIKLIKLARININ GÖSTERİLMESİ**



In [48]:
print(dataset['raceeth'].describe())

count      1570
unique        7
top       White
freq        882
Name: raceeth, dtype: object


**DATASET DEĞİŞKENİNDEKİ VERİLERİN X VE y DEĞİŞKENLERİNE ATANIP YAZDIRILMASI**

In [49]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
print(X)
print(y)

[[10 'White' 1.0 ... 0 808.0 35524]
 [10 'White' 0.0 ... 0 808.0 38557]
 [10 'White' 1.0 ... 0 808.0 52262]
 ...
 [10 'Hispanic' 1.0 ... 0 987.0 3241]
 [10 'White' 1.0 ... 0 987.0 59634]
 [10 'White' 1.0 ... 0 987.0 57743]]
[0 1 0 ... 0 0 0]


**NaN VERİ DÖNÜŞÜMÜ / DÖNÜŞÜM SONRASI X DEĞİŞKENİNİ YAZDIRMA**

In [50]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean')
imp.fit(X[:,2:25])
X[:,2:25]=imp.transform(X[:,2:25])

**DÖNÜŞÜMÜ SAĞLANAN NaN VERİLERLE BİRLİKTE YENİ X DİZİSİNİN ÇIKTISI**

In [51]:
print(X)

[[10 'White' 1.0 ... 0.0 808.0 35524.0]
 [10 'White' 0.0 ... 0.0 808.0 38557.0]
 [10 'White' 1.0 ... 0.0 808.0 52262.0]
 ...
 [10 'Hispanic' 1.0 ... 0.0 987.0 3241.0]
 [10 'White' 1.0 ... 0.0 987.0 59634.0]
 [10 'White' 1.0 ... 0.0 987.0 57743.0]]


In [52]:
print(X[1567])

[10 'Hispanic' 1.0 1.0 1.0 0.3306801736613603 1.0 0.8484429065743945
 0.3252730109204368 1.0 1.0 1.0 1.0 1.0 1.0 0.0 264.55555555555554
 24.701236263736263 1.0 1.0 0.0 987.0 3241.0]


**OBJECT DEĞERLERİN ONEHOTENCODING İLE DÖNÜŞÜMÜ**

In [53]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encode',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)
print(X[1567])

[[0.0 0.0 0.0 ... 0.0 808.0 35524.0]
 [0.0 0.0 0.0 ... 0.0 808.0 38557.0]
 [0.0 0.0 0.0 ... 0.0 808.0 52262.0]
 ...
 [0.0 0.0 0.0 ... 0.0 987.0 3241.0]
 [0.0 0.0 0.0 ... 0.0 987.0 59634.0]
 [0.0 0.0 0.0 ... 0.0 987.0 57743.0]]
[0.0 0.0 0.0 1.0 0.0 0.0 0.0 10 1.0 1.0 1.0 0.3306801736613603 1.0
 0.8484429065743945 0.3252730109204368 1.0 1.0 1.0 1.0 1.0 1.0 0.0
 264.55555555555554 24.701236263736263 1.0 1.0 0.0 987.0 3241.0]


**y ETİKET SÜTUNUNU BINARY POZİSYONUNA GETİRMEK İÇİN LABEL DÖNÜŞÜMÜ YAPMA**

> **NOT: ETİKET SÜTUNUMUZ ZATEN BINARY POZİSYONUNDA**




In [54]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 ... 0 0 0]


**ELDE EDİLEN X VE y DİZİLERİNE EĞİTİM VE TEST İŞLEMİ UYGULANIP EĞİTİM VERİLERİNİN ELDE EDİLMESİ**

In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1)

print(X_train)
print(X_train[0])

[[0.0 0.0 0.0 ... 1.0 1386.1485676215857 40265.0]
 [0.0 0.0 0.0 ... 0.0 846.0 537.0]
 [0.0 0.0 0.0 ... 0.0 1692.0 54319.0]
 ...
 [0.0 0.0 0.0 ... 0.0 1526.0 60555.0]
 [0.0 0.0 0.0 ... 1.0 502.0 41227.0]
 [0.0 0.0 0.0 ... 1.0 1720.0 50188.0]]
[0.0 0.0 0.0 0.0 0.0 0.0 1.0 10 0.0 1.0 1.0 0.0 1.0 1.0 0.0 1.0 1.0 1.0
 1.0 1.0 1.0 0.0 285.0 30.0 1.0 1.0 1.0 1386.1485676215857 40265.0]


In [56]:
print(X_train[1255])

[0.0 0.0 0.0 0.0 1.0 0.0 0.0 10 1.0 1.0 1.0 1.0 0.0 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 450.0 27.0 1.0 1.0 1.0 1720.0 50188.0]


**ÖZELLİK ÖLÇEKLEME İLE VERİLERİN İŞLENMESİ**

In [57]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,1:] = sc.fit_transform(X_train[:,1:])
X_test[:,1:] = sc.fit_transform(X_test[:,1:] )

print(X_train)

[[0.0 -0.20148578187619204 -0.3861746140943338 ... 1.3109594649014529
  0.041828815549302165 -0.3020746508287348]
 [0.0 -0.20148578187619204 -0.3861746140943338 ... -0.7628000916680997
  -0.6264634048100888 -2.723767382090613]
 [0.0 -0.20148578187619204 -0.3861746140943338 ... -0.7628000916680997
  0.42023976597408735 0.5546125633565863]
 ...
 [0.0 -0.20148578187619204 -0.3861746140943338 ... -0.7628000916680997
  0.21485829274693224 0.9347393221199036]
 [0.0 -0.20148578187619204 -0.3861746140943338 ... 1.3109594649014529
  -1.0520732047506993 -0.24343418547749823]
 [0.0 -0.20148578187619204 -0.3861746140943338 ... 1.3109594649014529
  0.4548824241087882 0.3027999205645298]]
